# fly.toml app configuration file generated for dream-app-main on 2024-01-19T11:10:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dream-app-main"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
