# fly.toml app configuration file generated for dream-app on 2024-02-12T20:49:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dream-app"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
